name: T-Donates
main: pl.timsixth.donates.DonatesPlugin
version: 1.3
author: timsixth (Idea by RokeR)
softdepend:
  - PlaceholderAPI
depend:
  - Vault
commands:
  donate:
    aliases:
      - donates
  adonates:
    aliases:
      - admindonates