name: T-Donates
main: pl.timsixth.donates.DonatesPlugin
version: '1.6.1'
author: timsixth (Idea by RokeR)
api-version: 1.13
softdepend:
  - PlaceholderAPI
depend:
  - Vault
commands:
  donate:
    aliases:
      - donates
  adonates:
    aliases:
      - admindonates