name: T-Donates
main: pl.timsixth.donates.DonatesPlugin
version: 1.2.2
author: timsixth (Idea by RokeR)
depend:
  - Vault
commands:
  donate:
    aliases:
      - donates
  adonates:
    aliases:
      - admindonates